

export const ADD_COMMENT = "ADDDISHCOMMENT";



export const LOAD_DISHES = "LOAD_DISHES";
export const DISHES_LOADING = "DISHES_LOADING";
export const LOAD_DISH_ERROR = "LOAD_DISH_ERROR"

export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const LOAD_COMMENTS_ERROR = "LOAD_COMMENTS_ERROR"


export const COMMENT_ADDING = "COMMENT_ADDING";
export const COMMENT_ADDED = "COMMENT_ADDED";
export const COMMENT_ADDED_FAILED = "COMMENT_ADDED_FAILED"

